GTCEuStartupEvents.registry("gtceu:material", event => {
    event.create("void")
        .gas()
        .fluid()
        .dust()
        .color(0x1b1b1b).secondaryColor(0x767676)
        .formula("∞")
    
    event.create("acetaldehyde")
        .fluid()
        .color(0xcbcbcb).iconSet(GTMaterialIconSet.DULL)
        .formula("C2H4O") 
    event.create("maleic_anhydride")
        .fluid()
        .color(0xbbffff).iconSet(GTMaterialIconSet.DULL)
        .formula("C4H2O3")
    event.create("diethyl_succinate")
        .fluid()
        .color(0xb6adad).iconSet(GTMaterialIconSet.DULL)
        .formula("(CH2COEt*)2")    

    event.create("vanadium_pentoxide")
        .dust()
        .color(0xff7d38).iconSet(GTMaterialIconSet.DULL)
        .formula("V2O5")    
    event.create("molybdenum_trioxide")
        .dust()
        .color(0xddd76a).secondaryColor(0x454322).iconSet(GTMaterialIconSet.DULL)
        .formula("MoO3") 

    event.create("cavum_tenebrae_air")
        .gas()
        .color(0x391b0f).iconSet(GTMaterialIconSet.DULL)
    event.create("unitas_air")
        .gas()
        .color(0xffe600).iconSet(GTMaterialIconSet.DULL)
    event.create("abydos_air")
        .gas()
        .color(0xcdb468).iconSet(GTMaterialIconSet.DULL)
    event.create("chulak_air")
        .gas()
        .color(0x98cecc).iconSet(GTMaterialIconSet.DULL)
    event.create("rima_air")
        .gas()
        .color(0x9aee3b).iconSet(GTMaterialIconSet.DULL)


    event.create("soot")
        .dust()
        .color(0x141414).iconSet(GTMaterialIconSet.DULL)
        .formula("C")
     event.create("sodium_disulfide")
        .dust()
        .color(0x823d50).iconSet(GTMaterialIconSet.DULL)
        .formula("Na2S2")
    event.create("polysulfide_rubber")
        .fluid()
        .color(0x70382f).iconSet(GTMaterialIconSet.DULL)
        .formula("HS((CH2)5O2S)3SH") 
    event.create("dichlorodiethylformal")
        .fluid()
        .color(0xe3e3e3).iconSet(GTMaterialIconSet.DULL)
        .formula("(Cl2(CH2)5O2)") 
    event.create("ethylene_chlorohydrin")
        .fluid()
        .color(0xfffce8).iconSet(GTMaterialIconSet.DULL)
        .formula("C2H5OCl") 
/*
    event.create("hypochlorous_acid")
        .fluid()
        .color(0xe8efef).iconSet("dull")
        .formula("HOCl") 
*/
    event.create("polysulfide_hermetic")
        .fluid()
        .polymer()
        .color(0xa37a6d).iconSet(GTMaterialIconSet.ROUGH)
        .fluidPipeProperties(530, 6500, true, true, false, false)
        .formula("(HS((CH2)5O2S)3SH)(CaCO3)2(Mg3Si4H2O12)2C") 

    event.create("phytogro")
        .fluid()
        .dust()
        .color(0x8acd53).secondaryColor(0xb8f82f).iconSet(GTMaterialIconSet.DULL);
})  