GTCEuStartupEvents.registry("gtceu:material", event => {
    event.create("gravel_slurry")
        .liquid()
        .color(0x645b5b).iconSet(GTMaterialIconSet.DULL)
    event.create("sand_slurry")
        .liquid()
        .color(0xd1ba8a).iconSet(GTMaterialIconSet.DULL)
    event.create("dirt_slurry")
        .liquid()
        .color(0x593d29).iconSet(GTMaterialIconSet.DULL)
    event.create("netherrack_slurry")
        .liquid()
        .color(0x411616).iconSet(GTMaterialIconSet.DULL)
    event.create("endstone_slurry")
        .liquid()
        .color(0xf6fabd).iconSet(GTMaterialIconSet.DULL)

    event.create("salty_mixture")
        .liquid()
        .color(0x4854da).iconSet(GTMaterialIconSet.DULL)
        .components("1x salt_water", "1x rock_salt")

    event.create("purified_water")
        .liquid()
        .color(0x4d629f).iconSet(GTMaterialIconSet.FLUID)
    event.create("95_pure_distilled_water")
        .liquid()
        .color(0x5d83f4).iconSet(GTMaterialIconSet.FLUID)
})