ServerEvents.recipes(event => {
    event.recipes.gtceu.matter_fabrication(`gtfte:uu_matter_no_boost`).circuit(1)
        .outputFluids(`gtceu:uu_matter 1`)
        .duration(10)
        .inputEU(100000)
        .addData("RequiredEnergy", 100000)
    event.recipes.gtceu.matter_fabrication(`gtfte:uu_matter_boost_1`).circuit(2)
        .outputFluids(`gtceu:uu_matter 2`)
        .itemInputs(`gtceu:scrap_gem`)
        .duration(10)
        .inputEU(120000)
        .addData("RequiredEnergy", 120000)
    event.recipes.gtceu.matter_fabrication(`gtfte:uu_matter_boost_2`).circuit(3)
        .outputFluids(`gtceu:uu_matter 10`)
        .itemInputs(`gtceu:scrap_box`)
        .duration(10)
        .inputEU(160000)
        .addData("RequiredEnergy", 160000)
});