GTCEuStartupEvents.registry(`gtceu:recipe_type`, event => {
// MARK: Register (Recipe Types)
    event.create(`barrel`)
        .category(`multiblock`)
        .setMaxIOSize(1, 1, 1, 1)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH);
	event.create(`growth_simulator`)
		.category(`multiblock`)
		.setMaxIOSize(2, 6, 2, 0)
		.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.COOLING);
	event.create(`sluicing`)
		.category(`multiblock`)
		.setMaxIOSize(2, 9, 1, 0)
		.setProgressBar(GuiTextures.PROGRESS_BAR_SIFT, FillDirection.UP_TO_DOWN)
		.setSound(GTSoundEntries.BATH);
	event.create(`terrestrial`)
		.category(`multiblock`)
		.setMaxIOSize(3, 1, 1, 0)
		.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.COOLING);
});

GTCEuStartupEvents.registry(`gtceu:machine`, event => {
// MARK: Register (Multiblocks)
    //-----Large barrel-----//
    event.create(`large_barrel`, `multiblock`)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(`barrel`)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock(`gtceu:treated_wood_planks`))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle(`RRR`, `F#F`, `F#F`, `F#F`)
            .aisle(`RRR`, `# #`, `# #`, `# #`)
            .aisle(`RRR`, `FCF`, `F#F`, `F#F`)
            .where(`C`, Predicates.controller(Predicates.blocks(definition.get())))
            .where(`#`, Predicates.blocks(`gtceu:treated_wood_planks`)
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1)))
            .where(`R`, Predicates.blocks(`gtceu:pump_deck`))
            .where(`F`, Predicates.blocks(`gtceu:treated_wood_frame`))
            .where(` `, Predicates.any())
            .build())
        .workableCasingModel(`gtceu:block/treated_wood_planks`, `gtceu:block/machines/brewery`)
    //-----Daycycle Simulation Chamber-----//
	event.create(`daycycle_simulation_chamber`, `multiblock`)
		.rotationState(RotationState.NON_Y_AXIS)
		.recipeType(`growth_simulator`)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_PERFECT_SUBTICK])
		.appearanceBlock(() => Block.getBlock(`gtceu:solid_machine_casing`))
		.pattern(definition => FactoryBlockPattern.start()
			.aisle(`###`, `#R#`, `#R#`, `#R#`, `###`)
			.aisle(`###`, `RGR`, `RSR`, `R R`, `#V#`)
			.aisle(`#C#`, `#R#`, `#R#`, `#R#`, `###`)
			.where(`C`, Predicates.controller(Predicates.blocks(definition.get())))
			.where(`#`, Predicates.blocks(`gtceu:solid_machine_casing`)
				.or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
				.or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1).setPreviewCount(1)))
            .where(`R`, Predicates.blocks(`gtceu:tempered_glass`))
			.where(`V`, Predicates.blocks(`kubejs:simple_ventilation`))
			.where(`G`, Predicates.blocks(`minecraft:grass_block`)
				.or(Predicates.blocks(`minecraft:dirt`)))
			.where(`S`, Predicates.blocks(`minecraft:oak_sapling`))
			.where(` `, Predicates.any())
			.build())
		.workableCasingModel(`gtceu:block/casings/solid/machine_casing_solid_steel`, `gtceu:block/machines/fermenter`)
    //-----Sluice-----//
	event.create(`sluice`, `multiblock`)
		.rotationState(RotationState.NON_Y_AXIS)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_PERFECT_SUBTICK])
		.recipeType(`sluicing`)
		.appearanceBlock(() => Block.getBlock(`gtceu:solid_machine_casing`))
		.pattern(definition => FactoryBlockPattern.start()
			.aisle(`###`, `###`, `###`)
			.aisle(`###`, `RWR`, `#R#`)
			.aisle(`###`, `RWR`, `#R#`)
			.aisle(`###`, `RWR`, `#R#`)
			.aisle(`###`, `RWR`, `#R#`)
			.aisle(`###`, `#C#`, `###`)
			.where(`C`, Predicates.controller(Predicates.blocks(definition.get())))
			.where(`#`, Predicates.blocks(`gtceu:solid_machine_casing`)
				.or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1).setPreviewCount(1)))
            .where(`R`, Predicates.blocks(`gtceu:tempered_glass`))
			.where(`W`, Predicates.blocks(`minecraft:water`))
			.where(` `, Predicates.any())
			.build())
		.workableCasingModel(`gtceu:block/casings/solid/machine_casing_solid_steel`, `gtceu:block/machines/sifter`)
    //-----Terrestrial Agglomeration Chamber-----//
event.create(`terrestrial`, `multiblock`)
		.rotationState(RotationState.NON_Y_AXIS)
		.recipeTypes([`terrestrial`])
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
		.appearanceBlock(() => Block.getBlock(`kubejs:manasteel_plated_livingrock_casing`))
		.pattern(definition => FactoryBlockPattern.start()
			.aisle(`A###A`, `R   R`, `A   A`, `  G  `)
			.aisle(`#####`, `  B  `, `     `, `     `)
			.aisle(`##R##`, ` BCB `, `     `, `G   G`)
			.aisle(`#####`, `  B  `, `     `, `     `)
			.aisle(`A###A`, `R   R`, `A   A`, `  G  `)
			.where(`C`, Predicates.controller(Predicates.blocks(definition.get())))
			.where(`#`, Predicates.blocks(`kubejs:manasteel_plated_livingrock_casing`)
				.or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
				.or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1).setPreviewCount(1)))
            .where(`R`, Predicates.blocks(`kubejs:manasteel_coil`))
			.where(`A`, Predicates.blocks(`chipped:ancient_gold_block`))
			.where(`B`, Predicates.blocks(`botania:livingrock_bricks_slab`))
			.where(`G`, Predicates.blocks(`botania:mana_pylon`))
			.where(` `, Predicates.any())
			.build())
		.workableCasingModel(`kubejs:block/casings/manasteel_plated_livingrock/manasteel_plated_livingrock_casing`, `kubejs:block/multiblock/terrastrial`)
});