GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
	event.create('terrestrial')
		.category('multiblock')
		.setMaxIOSize(3, 1, 1, 0)
		.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.COOLING);
});

GTCEuStartupEvents.registry('gtceu:machine', event => {
	event.create('terrestrial', 'multiblock')
		.rotationState(RotationState.NON_Y_AXIS)
		.recipeTypes(['terrestrial'])
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
		.appearanceBlock(() => Block.getBlock('kubejs:manasteel_plated_livingrock_casing'))
		.pattern(definition => FactoryBlockPattern.start()
			.aisle('A###A', 'R   R', 'A   A', '  G  ')
			.aisle('#####', '  B  ', '     ', '     ')
			.aisle('##R##', ' BEB ', '     ', 'G   G')
			.aisle('#####', '  B  ', '     ', '     ')
			.aisle('A#C#A', 'R   R', 'A   A', '  G  ')
			.where('C', Predicates.controller(Predicates.blocks(definition.get())))
			.where('#', Predicates.blocks('kubejs:manasteel_plated_livingrock_casing')
				.or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
				.or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1).setPreviewCount(1)))
            .where('R', Predicates.blocks('kubejs:manasteel_coil'))
			.where('A', Predicates.blocks('chipped:ancient_gold_block'))
			.where('B', Predicates.blocks('botania:livingrock_bricks_slab'))
			.where('E', Predicates.blocks('chipped:ancient_diamond_block'))
			.where('G', Predicates.blocks('botania:mana_pylon'))
			.where(' ', Predicates.any())
			.build())
		.workableCasingModel("kubejs:block/casings/manasteel_plated_livingrock/manasteel_plated_livingrock_casing", "kubejs:block/multiblock/terrastrial")
});
