StartupEvents.registry('block', event => {
    event.create('containment_coil', 'gtceu:coil')
        .temperature(0)
        .level(0)
        .energyDiscount(1) // 
        .tier(0)
        .coilMaterial(() => GTMaterials.get('rhodium_plated_palladium'))
        .texture('kubejs:block/coils/containment_coil/block')
        .hardness(2)
        .requiresTool(true)
        .tagBlock('forge:mineable/wrench')
        .tagBlock('minecraft:mineable/pickaxe')
        .soundType("metal")
    event.create('copper_coil', 'gtceu:coil')
        .temperature(433)
        .level(0)
        .energyDiscount(1) // 
        .tier(0)
        .coilMaterial(() => GTMaterials.get('copper'))
        .texture('kubejs:block/coils/copper/block')
        .hardness(2)
        .requiresTool(true)
        .tagBlock('forge:mineable/wrench')
        .tagBlock('minecraft:mineable/pickaxe')
        .soundType("metal")
    event.create('manasteel_coil', 'gtceu:coil')
        .temperature(0)
        .level(0)
        .energyDiscount(1) // 
        .tier(0)
        .coilMaterial(() => GTMaterials.get('manasteel'))
        .texture('kubejs:block/coils/manasteel/block')
        .hardness(3)
        .requiresTool(true)
        .tagBlock('forge:mineable/wrench')
        .tagBlock('minecraft:mineable/pickaxe')
        .soundType("metal")
    event.create('infinity_coil', 'gtceu:coil')
        .temperature(23400)
        .level(8)
        .energyDiscount(1) // 
        .tier(14)
        .coilMaterial(() => GTMaterials.get('infinity'))
        .texture('kubejs:block/coils/infinity/block')
        .hardness(3)
        .requiresTool(true)
        .tagBlock('forge:mineable/wrench')
        .tagBlock('minecraft:mineable/pickaxe')
        .soundType("metal")
})