GTCEuStartupEvents.registry(`gtceu:recipe_type`, event => {
	event.create(`fission`)
		.category(`multiblock`)
		.setMaxIOSize(5, 2, 2, 2)
		.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.ARC);
});

GTCEuStartupEvents.registry(`gtceu:machine`, event => {
	event.create(`fission_reactor`, `multiblock`)
		.rotationState(RotationState.NON_Y_AXIS)
		.generator(true)
		.recipeType(`fission`)
		.appearanceBlock(() => Block.getBlock(`kubejs:radiation_resistant_casing`))
		.pattern(definition => FactoryBlockPattern.start()
			.aisle(`#####`, `T#A#T`, `T#A#T`, `T#A#T`, `#####`)
			.aisle(`#####`, `#PFP#`, `#PFP#`, `#PFP#`, `#####`)
			.aisle(`#####`, `AFRFA`, `AFRFA`, `AFRFA`, `#####`)
			.aisle(`#####`, `#PFP#`, `#PFP#`, `#PFP#`, `#####`)
			.aisle(`##C##`, `T#A#T`, `T#A#T`, `T#A#T`, `#####`)
			.where(`C`, Predicates.controller(Predicates.blocks(definition.get())))
			.where(`#`, Predicates.blocks(`kubejs:radiation_resistant_casing`)
				.or(Predicates.abilities(PartAbility.OUTPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(3).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(3).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(3).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(4).setPreviewCount(1))
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1)))
            .where(`F`, Predicates.blocks(`kubejs:fission_reactor_rod`))
			.where(`R`, Predicates.blocks(`kubejs:containment_coil`))
			.where(`A`, Predicates.blocks(`gtceu:laminated_glass`))
			.where(`T`, Predicates.blocks(`gtceu:thaumium_frame`))
			.where(`P`, Predicates.blocks(`gtceu:ptfe_pipe_casing`))
			.where(` `, Predicates.any())
			.build())	
		.workableCasingModel(`kubejs:block/casings/radiation_resistant/radiation_resistant_casing`, `kubejs:block/multiblock/ring`)
});
